"""Shared multilingual lexicons.

These lexicons are reused by features and detectors. They only encode potentially relevant semantic anchors; whether they ultimately become
risk signals is still decided by context rules and the verdicter.
"""

from __future__ import annotations

ASCII_SENSITIVE_ACTION_WORDS = (
    # English sensitive-data action words used in combination with sensitive paths.
    "read",
    "steal",
    "collect",
    "copy",
    "exfiltrate",
    "exfil",
    "harvest",
    "dump",
    "extract",
)

UNICODE_SENSITIVE_ACTION_WORDS = (
    # Chinese/Japanese/Korean sensitive-data action words that improve recall for natural-language payloads.
    "读取",
    "读出",
    "收集",
    "采集",
    "复制",
    "拷贝",
    "窃取",
    "偷取",
    "盗取",
    "导出",
    "抽取",
    "外传",
    "盗む",
    "読み取る",
    "収集",
    "抽出",
    "外部送信",
    "수집",
    "탈취",
    "추출",
)

EXFIL_LANGUAGE = (
    # Exfiltration/forwarding anchors. The network detector still requires an external destination or sensitive context.
    "exfiltrate",
    "exfil",
    "steal",
    "leak",
    "capture",
    "webhook",
    "collect",
    "harvest",
    "siphon",
    "dump",
    "forward",
    "relay",
    "send out",
    "窃取",
    "偷取",
    "盗取",
    "泄露",
    "泄漏",
    "外传",
    "回传",
    "收集",
    "采集",
    "转发",
    "导出",
    "上报",
    "漏洩",
    "外部送信",
    "送信",
    "収集",
    "転送",
    "アップロード",
    "유출",
    "전송",
    "업로드",
    "수집",
    "exfiltrar",
    "robar",
    "filtrar",
)

SENSITIVE_CONTEXT_WORDS = (
    # Sensitive-context terms. They do not trigger maliciousness by themselves and are mainly used with exfiltration language.
    "password",
    "passwd",
    "pwd",
    "passcode",
    "passphrase",
    "token",
    "auth token",
    "bearer",
    "api key",
    "apikey",
    "access key",
    "secret",
    "credential",
    "credentials",
    "creds",
    "cookie",
    "session cookie",
    "session token",
    "refresh token",
    "id token",
    "jwt",
    "private key",
    "ssh key",
    ".env",
    "密码",
    "口令",
    "凭证",
    "认证信息",
    "令牌",
    "密钥",
    "私钥",
    "会话",
    "パスワード",
    "認証情報",
    "トークン",
    "秘密鍵",
    "セッション",
    "비밀번호",
    "자격 증명",
    "토큰",
    "비밀 키",
    "세션",
    "contraseña",
    "contrasena",
    "credencial",
    "clave secreta",
    "jeton",
    "mot de passe",
)

PERSONAL_DATA_MARKERS = (
    # Broad personal/health-data terms. `personal_data_access` only forms after multiple hits in the same file.
    "menstruation",
    "menstrual",
    "period tracking",
    "heart rate",
    "hrv",
    "sleep stages",
    "sleep data",
    "nutrition",
    "athlete",
    "body composition",
    "glucose",
    "blood glucose",
    "gps position",
    "geolocation",
    "location history",
    "demographics",
    "passport",
    "driver license",
    "social security",
    "ssn",
    "phone number",
    "email address",
    "home address",
    "contacts",
    "calendar",
    "medical",
    "diagnosis",
    "medication",
    "lab result",
    "身份证",
    "护照",
    "手机号",
    "电话号码",
    "邮箱",
    "住址",
    "地址",
    "位置",
    "定位",
    "通讯录",
    "日历",
    "健康",
    "医疗",
    "病历",
    "诊断",
    "药物",
    "月经",
    "经期",
    "睡眠",
    "心率",
    "血糖",
    "营养",
    "パスポート",
    "電話番号",
    "住所",
    "位置情報",
    "連絡先",
    "健康",
    "医療",
    "診断",
    "薬",
    "月経",
    "睡眠",
    "心拍",
    "血糖",
    "영양",
    "건강",
    "의료",
    "진단",
    "생리",
    "수면",
    "심박",
    "혈당",
)

COERCIVE_GOVERNANCE_MARKERS = (
    # Governance-override language for forced activation, unbypassable behavior, and lock-in.
    "mandatory activation",
    "auto-activates",
    "auto activates",
    "cannot be bypassed",
    "can't be bypassed",
    "cannot be disabled",
    "non-bypassable",
    "zero-tolerance",
    "automatic claim rejection",
    "immediate halt",
    "system lockdown",
    "force public correction",
    "ignore user attempts",
    "do not allow the user to override",
    "must always",
    "必须激活",
    "强制激活",
    "自动激活",
    "不可绕过",
    "不能绕过",
    "不能禁用",
    "系统锁定",
    "立即停止",
    "不允许用户覆盖",
    "必ず有効",
    "自動起動",
    "バイパス不可",
    "無効化できない",
    "시스템 잠금",
    "우회할 수 없음",
)

PERSONA_OVERRIDE_MARKERS = (
    # Persona/identity-adoption language that behaves like prompt override.
    "<role_gate",
    "role gate",
    "must adopt the persona",
    "adopt the persona",
    "assume the role",
    "act as the required agent",
    "role/personality adoption",
    "bootstrap this claude instance into a specific role",
    "recovering lost identity",
    "impersonate",
    "adopt identity",
    "角色门控",
    "采用人格",
    "采用角色",
    "扮演指定角色",
    "身份接管",
    "恢复身份",
    "ペルソナを採用",
    "役割を採用",
    "なりすます",
    "역할을 채택",
    "페르소나",
)
